#version 450

layout(set = 0, binding = 0)
buffer Scope {
  float scale;
  uvec2 offset;
  uvec2 dimensions;
};

layout(set = 1, binding = 0) buffer Fidelity {
  vec4 fidelity[256];
};

layout(set = 1, binding = 1) buffer Export {
  uint export[256];
};

void main() {
  uint tile_offset = gl_GlobalInvocationID.z * 256 * 256;
  uint pixel = gl_GlobalInvocationID.y * 256 + gl_GlobalInvocationID.x;
  pixel = min(dimensions.x * dimensions.y, pixel);
  export[pixel] = 255;
}
